package project.scheduler.Controller;

import java.time.Instant;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import project.scheduler.Repositories.TokenRepository;


@Controller // This means that this class is a Controller
@RequestMapping(path="/delete") // This means URL's start with /add (after Application path)
public class DeleteController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private TokenRepository tokenRepository;

  /*
  private RoomRepository roomRepository;
  private UserCourseRepository userCourseRepository;
  private RoomCourseRepository roomCourseRepository; */


  @GetMapping(path="/token")
  public @ResponseBody String deleteExpired() {
    Integer[] count = tokenRepository.findExpired(Instant.now());
    tokenRepository.deleteByIdIn(count);
    return String.format("Deleted %d expired entries%n", count.length);
  }
}
