package project.scheduler.Controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import jakarta.inject.Inject;
import project.scheduler.Repositories.CourseRepository;
import project.scheduler.Repositories.TokenRepository;
import project.scheduler.Repositories.UserRepository;
import project.scheduler.Tables.Course;
import project.scheduler.Tables.Token;
import project.scheduler.Tables.User;



@Controller // This means that this class is a Controller
@RequestMapping(path="/read") // This means URL's start with /user (after Application path)
public class ReadController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;
  @Inject
  private CourseRepository courseRepository;
  /*
  private RoomRepository roomRepository;
  private UserCourseRepository userCourseRepository;
  private RoomCourseRepository roomCourseRepository; */
  @Inject
  private TokenRepository tokenRepository;

  @GetMapping(path="/users")
  public @ResponseBody Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }
  

  @GetMapping(path="/tokens")
  public @ResponseBody Iterable<Token> getAllTokens() {
    // This returns a JSON or XML with the users
    return tokenRepository.findAll();
  }

  @GetMapping(path="/courses")
  public @ResponseBody Iterable<Course> getAllCourses() {
    // This returns a JSON or XML with the users
    return courseRepository.findAll();
  }
}
